language: python

python:
  - "3.8.3"

services:
  - postgresql

env:
  - DJANGO=3.0.7 DB=postgresql

install:
  - pip install -r requirements.txt

addons:
  apt:
    packages:
      firefox-geckodriver
      
before_script:
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz"
  - tar xfz geckodriver-v0.24.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - 'export DISPLAY=:99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3
  - psql -c "CREATE USER colette WITH PASSWORD 'dpbpass';" -U postgres
  - psql -c "ALTER USER colette CREATEDB;" -U postgres

script:
  - python manage.py test
